# -*- coding: utf-8 -*-
"""Starter File - GenAI for Stock Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bu04qtqp0l0o9xhv6haZz2pjvGwrt-r6
"""

from pathlib import Path

import pandas as pd

try:
    from IPython.display import display, Markdown
except ImportError:
    def display(obj):
        if isinstance(obj, pd.DataFrame):
            print(obj.to_string())
        else:
            print(obj)

    class Markdown:
        def __init__(self, text):
            self.text = text

        def _repr_markdown_(self):
            return self.text

        def __str__(self):
            return self.text


def _assets_csv_path() -> Path:
    base = Path(__file__).resolve().parent
    for name in ("assets 2025-07-31.csv", "assets.csv"):
        candidate = base / name
        if candidate.exists():
            return candidate
    colab = Path("/content/sample_data/assets 2025-07-31.csv")
    if colab.exists():
        return colab
    raise FileNotFoundError(
        "Portfolio CSV not found. Place 'assets 2025-07-31.csv' or 'assets.csv' "
        "in the same folder as this script."
    )


# Load the CSV file
df = pd.read_csv(_assets_csv_path())

# Display the first few rows to confirm it loaded correctly
display(df.head())

"""# New Section"""

import os
print("Files in /content/")
print(os.listdir('/content/'))

print("\nFiles in /content/sample_data/")
print(os.listdir('/content/sample_data/'))

import pandas as pd
import  yfinance as yf
from datetime import datetime
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd

# Load the CSV file from the project or Colab sample_data directory
data_df = pd.read_csv(_assets_csv_path())

# Display the first few rows to confirm it loaded correctly
display(data_df.head())

"""# FX Rates"""

# Retrieve the Exchange Rates
pair = "USDEUR=X"
yf.Ticker(pair).history(period="1d")

# Function to retrieve the FX-Rate
def get_fx_rate(from_currency, to_currency: str = "EUR") -> float:
    """
    Get the live FX rate from Yahoo. Returns 1.0 if the same currency is used.
    """
    if from_currency == to_currency:
        return 1.0
    pair = f"{from_currency}{to_currency}=X"
    try:
      rate = yf.Ticker(pair).history(period="1d")
      return rate["Close"].iloc[-1]
    except Exception:
      return np.nan

# Test the function with USD to EUR
get_fx_rate("USD", "EUR")

# Cache the FX rates
fx_cache = {}
for fx in df['Currency Yahoo'].unique():
  if fx == "EUR":
    fx_cache[fx] = 1.0
  else:
    fx_cache[fx] = get_fx_rate(fx)

    # Display the cache
    print("FX Cache:", fx_cache)

"""Retrive price data in Local currency"""

# Retrieve the price of one ticker
yf.Ticker("BTC-USD").history(period="1d")

# Build a function to fetch prices
def get_price_local(row) -> float:
  """
  Fetch the yahoo price in native currency and convert to local currency
  """
  try:
    price_native = (
        yf.Ticker(row['Ticker']).history(period = "1d")['Close'].iloc[-1]
    )
    return price_native * fx_cache[row['Currency Yahoo']]
  except Exception:
    print(f"Error fetching {row['Ticker']}")
    return np.nan

# Apply the function
df.apply(get_price_local, axis=1)

"""Gain Calculation"""

df.head()

# Compute the gains since last update and purchase
df["Price Today (EUR)"] = df.apply(get_price_local, axis=1)
df["Value Today (EUR)"] = df["Price Today (EUR)"] * df['Units']
# Gains in EUR since last update and Purchase
df["Gain since Last Update (EUR)"] = df["Value Today (EUR)"] - df["Value Last Update"]
df["Gain since Purchase (EUR)"] = df["Value Today (EUR)"] - df["Units"] * df["Purchase Price"]
# Compute the Relative gains since last update and purchase
df["Gain since Last Update (%)"] = df["Gain since Last Update (EUR)"] / df["Value Last Update"] * 100
df["Gain since Purchase (%)"] = df["Gain since Purchase (EUR)"] / (df["Units"] * df["Purchase Price"]) * 100

# Display
df.head()

# Compute the totals
total_cost = (df["Units"] * df["Purchase Price"]).sum()
total_gain_last = df["Gain since Last Update (EUR)"].sum()
total_gain_purchase = df["Gain since Purchase (EUR)"].sum()
total_gain_pct = (total_gain_purchase / total_cost * 100) if total_cost else 0.0
totals = {
    "Asset": "Total",
    "Ticker": "",
    "Gain since Last Update (EUR)": float(total_gain_last),
    "Gain since Purchase (EUR)": float(total_gain_purchase),
    "Gain since Purchase (%)": float(total_gain_pct),
}
totals_df = pd.DataFrame([totals])
totals_df

# Fetch the columns to show
columns = ["Asset", "Ticker", "Gain since Last Update (EUR)", "Gain since Purchase (EUR)", "Gain since Purchase (%)"]
report = pd.concat([df[columns], totals_df], ignore_index=True)
# Display report with just 2 floating cases
pd.options.display.float_format = '{:.2f}'.format
report

"""# Updates

### Updates to the current portfolio
"""

while True:
  response = input("Do you want to update the portfolio? (y/n) ").strip().lower()

  if response == "n":
    print("Exiting portfolio update process.")
    break
  elif response == "y":
    # User wants to update, proceed with the rest of the loop
    pass # No explicit action needed here, just let the code flow
  else:
    print("Invalid input. Please enter 'y' for yes or 'n' for no.")
    continue # Go back to the start of the loop

  print("\nCurrent Portfolio Assets:")
  for asset in df["Asset"]:
    print(f"- {asset}")

  # Ask the user to select which asset to update
  asset_name = input("\nWhich asset do you want to update? ").strip()

  # Check if the asset exists in our portfolio
  if asset_name not in df["Asset"].values:
    print(f"The asset '{asset_name}' does not exist in our portfolio.")
    continue

  # Ask for the units and price
  try:
    changed_units = float(input("How many units were bought (2) / sold (-2): "))
    new_purchase_price = float(input("What was the purchase price per unit (EUR): "))

    # Update units and average purchase price
    idx = df[df["Asset"] == asset_name].index[0]
    old_units = df.loc[idx, "Units"]

    # Prevent division by zero or negative units if selling too much
    if old_units + changed_units <= 0 and changed_units < 0:
      print(f"Warning: Cannot sell {abs(changed_units)} units of {asset_name}. You only have {old_units} units. Update cancelled for this asset.")
      continue
    elif old_units + changed_units < 0 and changed_units > 0:
      # This case should not happen if old_units is already positive, but as a safeguard
      print(f"Warning: Invalid unit calculation for {asset_name}. Total units would be negative. Update cancelled.")
      continue

    # Update units
    df.loc[idx, "Units"] = old_units + changed_units

    # Update the average purchasing price only if there are units remaining
    if df.loc[idx, "Units"] > 0:
        df.loc[idx, "Purchase Price"] = ((old_units * df.loc[idx, "Purchase Price"]) + (changed_units * new_purchase_price)) / (old_units + changed_units)
    else:
        # If all units are sold, reset purchase price or handle as desired (e.g., NaN)
        df.loc[idx, "Purchase Price"] = 0.0 # Or np.nan, depending on desired behavior

    # Display the new purchasing price and units to the user
    print(f"New purchasing price: {df.loc[idx, 'Purchase Price']}")
    print(f"New units: {df.loc[idx, 'Units']}")

  except Exception as e:
    print(f"An error occurred: {e}")

"""### Updating if there were new tickers added to Portfolio"""

# Add new assets to the portfolio
import numpy as np # Ensure np is imported if not already in the scope of this cell

while True:
  response = input("Do you want to add new assets to the portfolio? (y/n) ").strip().lower()
  if response == "y":
    try:
      asset_name = input("Asset name:").strip()
      ticker = input("Ticker:").strip()
      currency = input("Currency Yahoo:").strip().upper()
      units = float(input("Units:"))
      purchase_price = float(input("Purchase Price:"))

      # Create a new row
      new_row = {
          "Asset": asset_name,
          "Ticker": ticker,
          "Currency Yahoo": currency,
          "Units": units,
          "Purchase Price": purchase_price,
          "Currency Purchase": "EUR",
          "Price Last Update": np.nan,
          "Date Last Update": np.nan,
          "Value Last Update": np.nan,
          "Profit Last Update": np.nan
      }

      # Append to the dataframe
      df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
      print(f"Asset '{asset_name}' added successfully.")

    except ValueError:
      print("Invalid input for units or purchase price. Please enter numeric values.")
    except Exception as e:
      print(f"An unexpected error occurred: {e}")
  elif response == "n":
    print("Exiting asset addition process.")
    break
  else:
    print("Invalid input. Please enter 'y' for yes or 'n' for no.")

"""Exporting the CSV"""

from datetime import date

# Find the date of today
today = date.today().strftime("%Y-%m-%d")
today

# Update the columns
df["Price Last Update"] = df["Price Today (EUR)"]
df["Date Last Update"] = today
df["Value Last Update"] = df["Price Today (EUR)"] * df["Units"]
df.head()



# isolating the first 10 columns
df.iloc[:, :10].to_csv(f'assets {today}.csv', index=False)
df

"""### Finance and Stock Analysis

"""

# Build a function that retrieves prices and info
def get_history(ticker, period = "1y", interval = "1d"):
  """ Fetch historical data for a ticker
  """
  try:
    price_history = yf.Ticker(ticker).history(period = period, interval = interval)
    info = yf.Ticker(ticker).info
    return price_history, info
  except Exception:
    print(f"Error fetching {ticker}")
    return pd.DataFrame(), {}

price_history, info = get_history("AMZN")

price_history

info

"""### Moving Averge"""

# Compute the moving averages for the 50/100/200 days and display them
def compute_moving_averages(ticker):
  """ Compute the moving averages for the 50/100/200 days
  """
  # Computing the Moving averages
  price_history, _ = get_history(ticker)
  price_history["MA50"] = price_history["Close"].rolling(50).mean()
  price_history["MA100"] = price_history["Close"].rolling(100).mean()
  price_history["MA200"] = price_history["Close"].rolling(200).mean()

  # Retrieve the latest price and moving averages
  latest_price = price_history["Close"].iloc[-1]
  ma50 = price_history["MA50"].iloc[-1]
  ma100 = price_history["MA100"].iloc[-1]
  ma200 = price_history["MA200"].iloc[-1]

  # Display the results
  print(f"\n{ticker} - Moving average vs Price")
  print(f"Latest Price for {ticker}: ${latest_price}")
  print(f"MA50: {ma50:.2f}({'Above' if latest_price > ma50 else 'Below'})")
  print(f"MA100: {ma100:.2f}({'Above' if latest_price > ma100 else 'Below'})")
  print(f"MA200: {ma200:.2f}({'Above' if latest_price > ma200 else 'Below'})")
  return price_history

price_history, _ = get_history("AMZN")
price_history["Close"].rolling(50).mean()

compute_moving_averages("AMZN")

def plot_moving_averages(price_history, ticker):
  """ Plot the prices and moving averages
  """
  # Compute the Moving averages
  plt.figure(figsize=(12, 4))
  plt.plot(price_history.index, price_history["Close"], label="Closed_Price")
  plt.plot(price_history.index, price_history["MA50"], label="MA50")
  plt.plot(price_history.index, price_history["MA100"], label="MA100")
  plt.plot(price_history.index, price_history["MA200"], label="MA200")

  # Customize the plots
  plt.title(f"Price and Moving Averages for {ticker}")
  plt.xlabel("Date")
  plt.ylabel("Price")
  plt.legend()
  plt.grid(True)
  plt.show()

# Plot for all tickers in portfolio
for ticker in df["Ticker"]:
  price_history = compute_moving_averages(ticker)
  plot_moving_averages(price_history, ticker)

"""### Volality"""

# Build a functon to compute the ticker volatility
def compute_volatility(ticker, window=50):
  """
  Compute the ticker volatility
  """
  # Compute the ticker volatility
  price_history, _ = get_history(ticker)
  price_history["Returns"] = price_history["Close"].pct_change()
  returns = price_history["Returns"].dropna()
  # Compute the rolling volatitility
  rolling_volatility = returns.rolling(window=100).std() * np.sqrt(250)

  # Retrieve and Display the latest volatility
  latest_volatility = rolling_volatility.iloc[-1]
  print(f"Latest Volatility for {ticker}: {latest_volatility * 100:.1f}%")
  return latest_volatility

price_history, _ = get_history(ticker)
returns = price_history["Close"].pct_change().dropna()
# Compute the rolling volatitility
rolling_volatility = returns.rolling(window=100).std() * np.sqrt(250)

# Retrieve and Display the latest volatility
latest_volatility = rolling_volatility.iloc[-1]
print(f"Latest Volatility for {ticker}: {latest_volatility * 100:.1f}%")

# Test the function
compute_volatility("AMZN")

# Build a function to plot the volatiilities as a bar chart for my portfolio
def compute_volatility_plot():
  """
  Function that retrieves the volatitiles for all my protfolio tickers and plots them as a bar
  """
  volatilities = {}
  for ticker in df["Ticker"]:
    volatilities[ticker] = compute_volatility(ticker)

  # Plot them as a bar chart
  plt.figure(figsize=(10, 4))
  plt.bar(volatilities.keys(), volatilities.values())
  plt.xlabel("Ticker")
  plt.ylabel("Volatility (%)")
  plt.title("Portfolio Tickeers Volatility")
  plt.xticks(rotation=45)
  plt.grid(axis = "y", linestyle = "--", alpha = 0.6)
  plt.show()

compute_volatility_plot()

"""## P/E Ratio"""

import yfinance as yf
import numpy as np
# Build a function to retrieve the P/% ratio for a ticker
def pe_ratio(ticker):
  """
  Retrieve the P/E ratio for a ticker
  """
  try:
    info = yf.Ticker(ticker).info
    pe = info.get('trailingPE', np.nan)
    if np.isnan(pe):
      print(f"Warning, the ticker {ticker} has no PE Ratio (negative earnings, ETF or Crypto)")
    return pe
  except Exception:
    print(f"Error fetching {ticker}")
    return np.nan

# Display the PE ratios for our portfolio
for ticker in df["Ticker"]:
  pe = pe_ratio(ticker)
  print(f"PE Ratio for {ticker}: {pe}")

# Build a function to plot the PE ratios
def plot_pe_ratios():
    """
    Plot the PE ratios for all tickers in the portfolio
    """
    pe_ratios = {}
    for ticker in df["Ticker"]:
        pe_ratios[ticker] = pe_ratio(ticker)

    # Plot  the ratios
    plt.figure(figsize=(10, 4))
    plt.bar(pe_ratios.keys(), pe_ratios.values(), color = "red")
    plt.xlabel("Ticker")
    plt.ylabel("PE Ratio")
    plt.title("Portfolio Ticker PE Ratios")
    plt.xticks(rotation=45)
    plt.grid(axis="y", linestyle="--", alpha=0.6)
    plt.show()
plot_pe_ratios()

"""# Beta"""

# Defining a function to retrieve the Beta
def beta_values(ticker):
  """
  Funtion that retrieves the beta of stocks, if available
  """
  try:
    _, info = get_history(ticker)
    beta = info.get("beta", np.nan)
    return beta
  except Exception:
    print(f"Error fetching the beta of {ticker}")
    return np.nan

# Retrieve and show the beta for the portfolio
for ticker in df["Ticker"]:
  beta = beta_values(ticker)
  print(f"Beta for {ticker}: {beta}")

# Build a function to plot the Betas
def plot_betas():
  """
  Function that plots with a bar chart the betas
  """
  betas = {}
  for ticker in df["Ticker"]:
    betas[ticker] = beta_values(ticker)

  # Plot the Bar chart
  plt.figure(figsize=(10, 4))
  plt.bar(betas.keys(), betas.values(),
          color = "green")
  plt.xlabel("Ticker")
  plt.ylabel("Beta")
  plt.title("Portfolio Ticker Betas")
  plt.xticks(rotation=45)
  plt.grid(axis="y", linestyle="--", alpha=0.6)
  plt.show()
plot_betas()

"""# Sharpe Ratio"""

# Build a function to compute the Sharpe Ratio
def sharpe_ratio(ticker, risk_free_rate = 0.04):
  """
  Compute the Sharpe Ratio for a ticker
  """
  # Compute the Sharpe Ratio
  price_history, _ = get_history(ticker)

  # Compute the daily returns
  returns = price_history["Close"].pct_change().dropna()

  # Compute the annualized return
  avg_daily_return = returns.mean()
  annualized_return = avg_daily_return * 252
  volatility = returns.std() * np.sqrt(252)

  # Compute the annualized volatility
  annualized_volatility = returns.std() * np.sqrt(252)

  # Compute the Sharpe Ratio
  if volatility == 0 or pd.isna(volatility):
    return np.nan
  sharpe = (annualized_return - risk_free_rate) / volatility

  # Display and interpret the output
  if sharpe > 1:
    print(f"{ticker} has sharpe ratio {sharpe:.1f}, has a positive return that compensated for the volatility")
  elif sharpe > 0:
    print(f"{ticker} has sharpe ratio {sharpe:.1f}, has a positive return but with a high volatility")
  else:
    print(f"{ticker} has sharpe ratio {sharpe:.1f} has a negative return")
  return sharpe

# Test our function with our portfolio
for ticker in df["Ticker"]:
  sharpe_ratio(ticker)

"""# RSI"""

# Build a function to compute the RSI for a ticker
def rsi(ticker, window=14):
  """
  Computes the RSI for a ticker. Last date only
  """
  price_history, _ = get_history(ticker)
  delta = price_history["Close"].diff()

  # See how many days with gains and how many with loses
  gain = delta.where(delta > 0, 0)
  loss = -delta.where(delta < 0, 0)
  #avg_gain = gain.rolling

  # compute the rolling average gain and loss
  avg_gain = gain.rolling(window= window).mean()
  avg_loss = loss.rolling(window=window).mean()

  # Compute the RSI
  rs = avg_gain / avg_loss
  rsi = 100 - (100 / (1 + rs))

  return rsi.iloc[-1]

price_history, _ = get_history("MSFT")
price_history["Close"].diff()

rsi("MSFT")

# Test the  function to retrieve the RSI for the portfolio
for ticker in df["Ticker"]:
  rsi_value = rsi(ticker)
  print(f"RSI for {ticker}: {rsi_value:.2f}")

# Build a functon to visualize the RSI of each portfolio Ticker
def plot_rsi():
  """
  Plot the RSI fro all tickers in the portfolio
  """
  rsi_values = {}
  for ticker in df["Ticker"]:
    rsi_values[ticker] = rsi(ticker)

  # Plot the RSI with a bar chart
  plt.figure(figsize=(10, 4))
  plt.bar(rsi_values.keys(), rsi_values.values(), color = "orange")
  plt.axhline(y = 30, color = "g", linestyle = "--", label="Oversold")
  plt.axhline(y = 70, color = "r", linestyle = "--", label="Overbought")
  plt.legend()
  plt.xlabel("Ticker")
  plt.ylabel("RSI")
  plt.title("Portfolio Ticker RSI (14-day)")
  plt.xlabel("Ticker")
  plt.ylabel("RSI")
  plt.xticks(rotation=45)
  plt.grid(axis="y", linestyle="--", alpha=0.6)
  plt.show()
plot_rsi()

"""# MACD Crossover"""

# Build a function to compute the MACD
def compute_macd(ticker, short_window=12, long_window=26, signal_window=9):
  """
  Compute the MACD for a ticker
  """
  price_history, _ = get_history(ticker)
  close = price_history["Close"]
  # Compute the moving averaages
  short_ema = close.ewm(span=short_window, adjust=False).mean()
  long_ema = close.ewm(span=long_window, adjust=False).mean()

  # Compute the MACD and Signal Lines
  price_history['MACD'] = short_ema - long_ema
  price_history['Signal'] = price_history['MACD'].ewm(span=signal_window, adjust=False).mean()

  # Latest Crossover
  macd_val = price_history['MACD'].iloc[-1]
  signal_val = price_history['Signal'].iloc[-1]
  if macd_val > signal_val:
    status = "Bullish"
  elif macd_val < signal_val:
    status = "Bearish"
  else:
    status = "Neutral"

  # Display the results
  print(f"\n{ticker} - MACD Crossover")
  print(f"MACD for {ticker}: {macd_val:.2f}")
  print(f"Signal for {ticker}: {signal_val:.2f}")
  print(f"Status for {ticker}: {status}")

  return price_history

# Build a function to visualize the MACD and Signal
def plot_macd(price_history, ticker):
  """
  Plot the MACD and Signal for a ticker
  """
  plt.figure(figsize=(12, 4))
  plt.plot(price_history.index, price_history["MACD"], label="MACD", color="blue")
  plt.plot(price_history.index, price_history["Signal"], label="Signal", color = "red")
  plt.axhline(y=0, color="black", linestyle="--")
  plt.title(f"MACD and Signal for {ticker}")
  plt.xlabel("Date")
  plt.ylabel("MACD/Signal")
  plt.legend()
  plt.grid(True)


  plt.show()

# Test the funciton
for ticker in df["Ticker"]:
  macd = compute_macd(ticker)
  plot_macd(macd, ticker)

"""# AI Recommendations"""

# Requires: pip install langchain_openai python-dotenv (see requirements.txt)

import os
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent / ".env")

from utils import (
    build_portfolio_kpi_dataframe,
    generate_portfolio_ai_markdown,
    format_overall_portfolio_note_heuristic,
)

# Aggregate KPIs for the current portfolio (quiet — no per-ticker print spam)
_prices = df["Price Today (EUR)"].tolist() if "Price Today (EUR)" in df.columns else None
df_current_portfolio = build_portfolio_kpi_dataframe(
    df["Ticker"].tolist(),
    assets=df["Asset"].tolist(),
    prices_today=_prices,
)
display(df_current_portfolio)

"""### Possible New Investments"""

new_tickers_input = input("Please enter new tickers separated by commas (or press Enter to skip): ")
new_ticker_list = [t.strip().upper() for t in new_tickers_input.split(",") if t.strip()]

if new_ticker_list:
    data = build_portfolio_kpi_dataframe(new_ticker_list)
else:
    data = pd.DataFrame()
display(data)

# Generate AI markdown (includes mandatory ## Overall Portfolio Note)
try:
    ai_markdown = generate_portfolio_ai_markdown(df_current_portfolio, data)
except ValueError as exc:
    print(exc)
    ai_markdown = (
        "# Portfolio Analysis (offline)\n\n"
        + format_overall_portfolio_note_heuristic(df_current_portfolio)
    )

print(ai_markdown)
display(Markdown(ai_markdown))